language: php
dist: trusty
php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
matrix:
  include:
    - php: 5.3
      dist: precise
before_script: "composer install"
script: "composer run-script test -- --colors --coverage-text"
